spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

hibernate:
  dialect: org.hibernate.dialect.MySQL5Dialect
  hbm2ddl:
    auto: update
  show_sql: true

management:
  security:
    enabled: false

endpoints:
  shutdown:
    enabled: true

logging:
  level:
    com:
      jstudyplanner: DEBUG

campus:
  url: http://localhost:8090
  getall: campusService/getAllCampuses